openapi: 3.0.3
info:
    title: GFE REST Services
    description: |
        REST services for curating and computing with GFE
    version: 2.0.0
    contact:
        email: cibmtr-pypi@nmdp.org
    license:
        name: GNU Lesser General Public License version 3
        url: https://opensource.org/licenses/lgpl-3.0.html
servers:
    -   url: 'http://localhost:8080'
tags:
    -   name: IMGT
        description: "Available IPD-IMGT/HLA Database releases"
    -   name: GFE
        description: Create and Retrieve GFE
    -   name: "Sequence Annotation"
        description: Annotation by sequence (Coming Soon)
paths:
    /ipd-imgt-hla-versions:
        get:
            summary: IPD-IMGT/HLA Database versions in the GFE-DB
            tags:
                - IMGT
            operationId: api.imgt_versions
            description: Versions of IPD-IMGT/HLA Database Alleles in GFE DB

            responses:
                200:
                    description: Version Numbers of Available IPD-IMGT/HLA Database
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    imgt_versions:
                                        description: IPD-IMGT/HLA Database Versions
                                        type: array
                                        items:
                                            type: string
                                        example:
                                            - "3450"
                                            - "3460"
                                            - "3470"
                500:
                    description: "Internal Server Error"
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        description: Error Message
                                        type: string
                                        example: "Database Unreachable"

    /ipd/{ipd_name}:
        get:
            summary: Get GFE for a IPD-IMGT/HLA HLA name
            tags:
                - GFE
            operationId: api.gfe_from_ipd
            description: For a given IPD-IMGT/HLA Allele name, return the corresponding GFE
            parameters:
                -   name: ipd_name
                    in: path
                    description: IPD-IMGT/HLA Database Allele name
                    required: true
                    schema:
                        type: string
                    style: simple
                    example: "HLA-A*01:01:01:08"
            responses:
                200:
                    description: GFE from IPD-IMGT/HLA allele name
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    locus:
                                        description: Gene Locus
                                        type: string
                                        example: "HLA-A"
                                    gfe:
                                        description: GFE Name
                                        type: string
                                        example: "HLA-Aw878-8-363-912-830-2901-1044-581-151-324-198-9-316-80-508-43-151"
                                    allele:
                                        description: IPD-IMGT/HLA Allele Name
                                        type: string
                                        example: "HLA-A*01:01:01:08"
                                    imgt_versions:
                                        description: IPD-IMGT/HLA Database Versions
                                        type: array
                                        items:
                                            type: string
                                        example:
                                            - "3460"
                                            - "3470"

    /gfe/locus/{gene}:
        get:
            summary: GFEs and IPD Allele Names for a gene
            tags:
                - GFE
            operationId: api.all_locus_gfe
            description: Get all GFEs and IPD Allele Names for a gene
            parameters:
                -   name: gene
                    in: path
                    description: IPD Allele Gene Name
                    required: true
                    schema:
                        type: string
                    style: simple
                    example: "HLA-A"
                -   name: version
                    in: query
                    description: IPD-IMGT/HLA version number
                    schema:
                        type: string
                    example: "3530"
            responses:
                200:
                    description: List of IPD Allele names and their corresponding GFEs
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    locus:
                                        description: Gene Locus
                                        type: string
                                        example: "HLA-A"
                                    GFEs:
                                        description: List of IPD Alleles and GFE
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                gfe:
                                                    description: GFE Name
                                                    type: string
                                                    example: "HLA-Aw878-8-363-912-830-2901-1044-581-151-324-198-9-316-80-508-43-151"
                                                who:
                                                    description: IPD Allele Name
                                                    type: string
                                                    example: "HLA-A*01:01:01:08"
                                                releases:
                                                    description: IPD release list
                                                    type: array
                                                    items:
                                                        type: string
                                                        example: "3530"

    /gfe/sequence/{gfe}:
        get:
            summary: Sequence For a GFE
            tags:
                - GFE
            operationId: api.gfe_sequence
            description: Get Sequence for a GFE
            parameters:
                - name: gfe
                  in: path
                  description: GFE name
                  required: true
                  schema:
                      type: string
                  style: simple
                  example: "HLA-Aw0-1-0-29-0-1-0-1-0-1-0-0-0-0-0-0-0"
            responses:
                200:
                    description: Sequence corresponding to a GFE
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    gfe:
                                        description: GFE
                                        type: string
                                        example: "HLA-Aw99-8-363-912-830-2901-128-581-151-324-198-9-316-80-508-43-30"
                                    sequence:
                                        description: Sequence for the GFE
                                        type: string
                                        example: "CAGGAGCAGAGGGGTCAGGGCGAAGTCCCAGGGCCCCAGGCGTGGCTCTCAGGGTCTCAGGCCCCGAAGGCGGTGTATGGATTGGGGAGTCCCAGCCTTGGGGATTCCCCAACTCCGCAGTTTCTTTTCTCCCTCTCCCAACCTACGTAGGGTCCTTCATCCTGGATACTCACGACGCGGACCCAGTTCTCACTCCCATTGGGTGTCGGGTTTCCAGAGAAGCCAATCAGTGTCGTCGCGGTCGCTGTTCTAAAGTCCGCACGCACCCACCGGGACTCAGATTCTCCCCAGACGCCGAGGATGGCCGTCATGGCGCCCCGAACCCTCCTCCTGCTACTCTCGGGGGCCCTGGCCCTGACCCAGACCTGGGCGGGTGAGTGCGGGGTCGGGAGGGAAACCGCCTCTGCGGGGAGAAGCAAGGGGCCCTCCTGGCGGGGGCGCAGGACCGGGGGAGCCGCGCCGGGAGGAGGGTCGGGCAGGTCTCAGCCACTGCTCGCCCCCAGGCTCCCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAGCCCCGCTTCATCGCCGTGGGCTACGTGGACGACACGCAGTTCGTGCGGTTCGACAGCGACGCCGCGAGCCAGAAGATGGAGCCGCGGGCGCCGTGGATAGAGCAGGAGGGGCCGGAGTATTGGGACCAGGAGACACGGAATATGAAGGCCCACTCACAGACTGACCGAGCGAACCTGGGGACCCTGCGCGGCTACTACAACCAGAGCGAGGACGGTGAGTGACCCCGGCCCGGGGCGCAGGTCACGACCCCTCATCCCCCACGGACGGGCCAGGTCGCCCACAGTCTCCGGGTCCGAGATCCACCCCGAAGCCGCGGGACTCCGAGACCCTTGTCCCGGGAGAGGCCCAGGCGCCTTTACCCGGTTTCATTTTCAGTTTAGGCCAAAAATCCCCCCGGGTTGGTCGGGGCGGGGCGGGGCTCGGGGGACTGGGCTGACCGCGGGGTCGGGGCCAGGTTCTCACACCATCCAGATAATGTATGGCTGCGACGTGGGGCCGGACGGGCGCTTCCTCCGCGGGTACCGGCAGGACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGACCTGCGCTCTTGGACCGCGGCGGACATGGCAGCTCAGATCACCAAGCGCAAGTGGGAGGCGGTCCATGCGGCGGAGCAGCGGAGAGTCTACCTGGAGGGCCGGTGCGTGGACGGGCTCCGCAGATACCTGGAGAACGGGAAGGAGACGCTGCAGCGCACGGGTACCAGGGGCCACGGGGCGCCTCCCTGATCGCCTATAGATCTCCCGGGCTGGCCTCCCACAAGGAGGGGAGACAATTGGGACCAACACTAGAATATCACCCTCCCTCTGGTCCTGAGGGAGAGGAATCCTCCTGGGTTTCCAGATCCTGTACCAGAGAGTGACTCTGAGGTTCCGCCCTGCTCTCTGACACAATTAAGGGATAAAATCTCTGAAGGAGTGACGGGAAGACGATCCCTCGAATACTGATGAGTGGTTCCCTTTGACACCGGCAGCAGCCTTGGGCCCGTGACTTTTCCTCTCAGGCCTTGTTCTCTGCTTCACACTCAATGTGTGTGGGGGTCTGAGTCCAGCACTTCTGAGTCTCTCAGCCTCCACTCAGGTCAGGACCAGAAGTCGCTGTTCCCTTCTCAGGGAATAGAAGATTATCCCAGGTGCCTGTGTCCAGGCTGGTGTCTGGGTTCTGTGCTCTCTTCCCCATCCCGGGTGTCCTGTCCATTCTCAAGATGGCCACATGCGTGCTGGTGGAGTGTCCCATGACAGATGCAAAATGCCTGAATTTTCTGACTCTTCCCGTCAGACCCCCCCAAGACACATATGACCCACCACCCCATCTCTGACCATGAGGCCACCCTGAGGTGCTGGGCCCTGGGCTTCTACCCTGCGGAGATCACACTGACCTGGCAGCGGGATGGGGAGGACCAGACCCAGGACACGGAGCTCGTGGAGACCAGGCCTGCAGGGGATGGAACCTTCCAGAAGTGGGCGGCTGTGGTGGTGCCTTCTGGAGAGGAGCAGAGATACACCTGCCATGTGCAGCATGAGGGTCTGCCCAAGCCCCTCACCCTGAGATGGGGTAAGGAGGGAGATGGGGGTGTCATGTCTCTTAGGGAAAGCAGGAGCCTCTCTGGAGACCTTTAGCAGGGTCAGGGCCCCTCACCTTCCCCTCTTTTCCCAGAGCTGTCTTCCCAGCCCACCATCCCCATCGTGGGCATCATTGCTGGCCTGGTTCTCCTTGGAGCTGTGATCACTGGAGCTGTGGTCGCTGCCGTGATGTGGAGGAGGAAGAGCTCAGGTGGAGAAGGGGTGAAGGGTGGGGTCTGAGATTTCTTGTCTCACTGAGGGTTCCAAGCCCCAGCTAGAAATGTGCCCTGTCTCATTACTGGGAAGCACCTTCCACAATCATGGGCCGACCCAGCCTGGGCCCTGTGTGCCAGCACTTACTCTTTTGTAAAGCACCTGTTAAAATGAAGGACAGATTTATCACCTTGATTACGGCGGTGATGGGACCTGATCCCAGCAGTCACAAGTCACAGGGGAAGGTCCCTGAGGACAGACCTCAGGAGGGCTATTGGTCCAGGACCCACACCTGCTTTCTTCATGTTTCCTGATCCCGCCCTGGGTCTGCAGTCACACATTTCTGGAAACTTCTCTGGGGTCCAAGACTAGGAGGTTCCTCTAGGACCTTAAGGCCCTGGCTCCTTTCTGGTATCTCACAGGACATTTTCTTCCCACAGATAGAAAAGGAGGGAGTTACACTCAGGCTGCAAGTAAGTATGAAGGAGGCTGATGCCTGAGGTCCTTGGGATATTGTGTTTGGGAGCCCATGGGGGAGCTCACCCACCCCACAATTCCTCCTCTAGCCACATCTTCTGTGGGATCTGACCAGGTTCTGTTTTTGTTCTACCCCAGGCAGTGACAGTGCCCAGGGCTCTGATGTGTCTCTCACAGCTTGTAAAGGTGAGAGCTTGGAGGGCCTGATGTGTGTTGGGTGTTGGGTGGAACAGTGGACACAGCTGTGCTATGGGGTTTCTTTGCGTTGGATGTATTGAGCATGCGATGGGCTGTTTAAGGTGTGACCCCTCACTGTGATGGATATGAATTTGTTCATGAATATTTTTTTCTATAGTGTGAGACAGCTGCCTTGTGTGGGACTGAGAGGCAAGAGTTGTTCCTGCCCTTCCCTTTGTGACTTGAAGAACCCTGACTTTGTTTCTGCAAAGGCACCTGCATGTGTCTGTGTTCGTGTAGGCATAATGTGAGGAGGTGGGGAGAGCACCCCACCCCCATGTCCACCATGACCCTCTTCCCACGCTGACCTGTGCTCCCTCTCCAATCATCTTTCCTGTTCCAGAGAGGTGGGGCTGAGGTGTCTCCATCTCTGTCTCAACTTCATGGTGCACTGAGCTGTAACTTCTTCCTTCCCTATTAAAA"
