---
swagger: "2.0"
info:
  title: GFE REST Services
  description: |
    REST services for curating and computing with GFE
  version: 0.0.2
  contact:
    email: cibmtr-pypi@nmdp.org
  license:
    name: GNU Lesser General Public License version 3
    url: https://opensource.org/licenses/lgpl-3.0.html
basePath: /v1
tags:
  - name: IMGT
    description: "Available IMGT DB releases"
  - name: Sequence Annotation
    description: "Annotation by sequence"
  - name: Features
    description: "Features associated with a locus"
  - name: GFE
    description: "Create and Retrieve GFE"
paths:
  /imgt-versions:
    get:
      summary: Get available IMGT DB versions
      description: |
        Returns all the inlcuded IMGT Database versions
      tags:
        - IMGT
      operationId: allreleases_get
      consumes:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              type: string
            example:
              [
                  "3.43.0",
                  "3.42.0",
                  "3.41.0"
              ]
        404:
          description: "Failed to load all db releases"
      x-swagger-router-controller: "api.controllers.all_releases_controller"

  /annotation/{locus}:
    post:
      summary: Annotate a sequence for a locus
      tags:
        - "Sequence Annotation"
      operationId: gfeAnnotation_post
      consumes:
        - "application/json"
      parameters:
        - name: locus
          in: path
          description: HUGO gene name
          required: true
          type: string
        - name: gene_family
          description: "Gene Family, eg: HLA, KIR"
          type: string
          in: query
          required: false
        - in: body
          name: sequence
          required: true
          description: Sequence to annotate
          schema:
            type: object
            required:
              - sequence
            properties:
              sequence:
                type: string
                example:
                  GCTCTCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAG
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Annotation"
        404:
          description: "Failed to annotate the sequence"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "api.controllers.gfe_annotation_controller"

  /gfe:
    post:
      summary: Create a GFE
      description: |
        Create a GFE from the given sequence  and locus
      tags:
        - GFE
      operationId: gfe_create_post
      consumes:
        - application/json
      parameters:
        - name: sequence
          in: body
          description: Consensus sequence
          required: true
          schema:
            type: object
            required:
              - sequence
            properties:
              sequence:
                type: string
                example:
                  GCTCTCACTCCATGAGGTATTTCTTCACATCCGTGTCCCGGCCCGGCCGCGGGGAG
              locus:
                type: string
                description: Valid HLA locus
                example:
                  HLA-A
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Annotation"
        404:
          description: Failed to create GFE from sequence and locus
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "api.controllers.gfe_create_controller"

  /gfe/{gfe}:
    get:
      summary: Get GFE
      description: |
        Get allele and features corresponding to a GFE
      tags:
        - GFE
      operationId: find_features_get
      consumes:
        - application/json
      parameters:
        - name: gfe
          in: path
          description: Valid GFE
          required: true
          type: string
        - name: imgt_release_version
          in: query
          description: Valid IMGT version
          required: false
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Annotation"
        404:
          description: "Failed to get GFE and HLA for the IMGT version and locus"
      x-swagger-router-controller: "api.controllers.find_features_controller"


definitions:
  Error:
    type: object
    required:
      - "Message"
      - "gfedb_version"
      - "imgtdb_version"
      - "pygfe_version"
    properties:
      Message:
        type: string
      pygfe_version:
        type: string
      gfedb_version:
        type: string
      imgtdb_version:
        type: string
      log:
        type: array
        items:
          type: string
      type:
        type: string
  Annotation:
    type: object
    properties:
      features:
        type: array
        items:
          $ref: '#/definitions/Feature'
      gfe:
        type: string
      imgt_name:
        type: string
      imgtdb_version:
        type: string
    example:
      gfe: HLA-Aw2-1-1-1-43-1-1-1-1-1-1-1-1-1-1-1-4
      imgt_name: 'HLA-A*01:01:01:01'
      features:
        - accession: 1
          locus: HLA-A
          rank: 1
          term: exon
          sequence: ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG
        - accession: 2
          locus: HLA-A
          rank: 1
          sequence: ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG
          term: exon
      imgtdb_version: 3.41.0
  Feature:
    type: object
    properties:
      locus:
        type: string
      accession:
        type: integer
      rank:
        type: integer
      sequence:
        type: string
      term:
        type: string
    example:
      accession: 1
      locus: "HLA-A"
      rank: 1
      sequence: "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG"
      term: "exon"
